import { CoreSeoPage, type CoreFaq, type CoreSection } from "@/components/steal-an-egg/CoreSeoPage";
import { buildMetadata } from "@/lib/seo";

const title = "Red Panda in Steal An Egg – How to Get & Pet Guide";
const description = "Learn how to get the Red Panda in Steal An Egg, including its reported source, rarity, pet income context, progression value, and answers to common questions.";
const pathname = "/pets/red-panda/";
export const metadata = buildMetadata({ title, description, pathname });

const sections: CoreSection[] = [
  { title: "What Is Red Panda in Steal An Egg?", subsections: [
    { title: "The pet behind the search", paragraphs: ["Red Panda is a pet name reported in Steal An Egg's Cherry Blossom coverage. A search for red panda steal an egg usually asks which source leads to the pet, how rare the result is and whether it helps progression. This page stays with the individual pet. The broad pets index serves players comparing the full roster, while the Sakura Event page explains the wider biome and its event mechanics.", "Treat a picture of a red panda, an egg label and a hatched Red Panda as three different observations. A video thumbnail can establish that a creator showed the animal, but not the exact egg object or odds. A reliable pet record starts with the name visible on the selected result panel and preserves the source context alongside it."], links: [{ href: "/pets/", label: "Browse all pet records" }] },
  ] },
  { title: "How to Get Red Panda", subsections: [
    { title: "Follow the Cherry Blossom lead", paragraphs: ["Multiple public pet indexes place Red Panda among Cherry Blossom results. That gives players a useful biome to investigate, but a complete path still needs the current egg or source label in game. Travel to the Cherry Blossom area when it is accessible in your server, inspect the available eggs or interaction prompts and check which result actually hatches. Do not mistake the guardian, decorative wildlife or another shop pool for the Red Panda source.", "If the area is beyond your comfortable route, train enough movement to carry an egg home. Repeated safe returns often beat one risky attempt at a distant target. The exact Speed gate and spawn timer for a Red Panda source are not confirmed in this guide, so the live entrance and current object prompt take priority over a copied number."], links: [{ href: "/updates/sakura-event/", label: "Review Cherry Blossom context" }] },
  ] },
  { title: "Red Panda Egg or Source", subsections: [
    { title: "Separate player wording from an official object", paragraphs: ["Players say Red Panda egg when they mean the egg that could yield the Red Panda pet. That search phrase does not prove an in-game object with exactly that title. In some versions or guides, a biome's egg name and its hatch result are different. Check the item name before pickup, the hatch screen and the final selected pet panel. Record all three if you want to verify the source path.", "A reported Cherry Blossom association should not be expanded into a guaranteed hatch pool. One player finding Red Panda there confirms a result in that context, but not the chance of it happening again. If the source is part of a limited event, verify that the active game still offers it before spending on a route that may have changed."], links: [{ href: "/eggs/", label: "Compare egg terminology" }] },
  ] },
  { title: "Red Panda Rarity", subsections: [
    { title: "Read the tier on the current pet panel", paragraphs: ["Recent independent pet indexes commonly list Red Panda as Mythic. This is useful context, but the live in-game rarity label should settle the question for a particular result after a patch. Rarity describes its class in the game's ladder; it does not by itself specify income, source odds or whether a copy is more valuable than a higher-tier pet with different modifiers.", "If a screenshot shows an unusual color or size, do not infer a new tier from appearance. Check the word next to the pet, then compare that tier with the site's rarity guide. A standard Red Panda and a modified one should still be identified by the same pet name unless the game explicitly changes it."], links: [{ href: "/rarities/", label: "Read the rarity order" }] },
  ] },
  { title: "Red Panda Stats and Income", subsections: [
    { title: "Use your selected pet value", paragraphs: ["Public income figures for Red Panda are snapshots from particular guides and game versions. This page does not freeze one as a universal Money per Second value. After hatching, open the selected pet panel and note its current income, size and any visible mutation or boost. Compare like with like if you are deciding which pen slot it deserves. A difference between your pet and a guide screenshot can reflect modifiers rather than a wrong name.", "The game's pet loop makes income relevant because earnings fund upgrades and movement. Yet raw income is only one part of a useful acquisition. Time spent reaching the source, risk of losing an egg and the chance of obtaining the desired result matter too. None of those is turned into a fixed Red Panda spawn or hatch rate here."], links: [{ href: "/pets/best-pets/", label: "Compare pet value criteria" }] },
  ] },
  { title: "Is Red Panda Good?", subsections: [
    { title: "Judge the upgrade it enables", paragraphs: ["Red Panda is worthwhile when the copy you obtain improves your pen or completes a collection goal at a manageable cost. If its displayed income beats your weakest active pet, it may help finance the next upgrade. If your current lineup already earns more, keeping Red Panda may be about the index or collection rather than immediate cash. That is a decision based on your account, not a universal ranking.", "Do not replace a stronger pet solely because a new hatch has a rarer-looking model. Check the current panel and compare under the same boosts. Consider whether another Cherry Blossom target or a safer earlier biome provides a more repeatable income step. A good route is one you can finish consistently, especially while learning an unfamiliar area."], links: [{ href: "/pets/rarest-pets/", label: "Separate rarity from value" }] },
  ] },
  { title: "Best Tips for Getting Red Panda", subsections: [
    { title: "Document the source while you play", paragraphs: ["Before a run, clear an inventory or pen space and identify the safest return path. In the biome, read the object label rather than relying on a character model seen from a distance. After pickup, prioritize returning the egg over investigating another target. A successful carry gives you evidence and a chance to hatch; a lost egg gives neither.", "When Red Panda hatches, capture the result screen and the selected pet panel together if possible. The paired evidence can establish source, rarity and displayed income for that version without inventing a global number. If the hatch produces a different pet, note that too; it helps distinguish a mixed pool from a guaranteed Red Panda source."], links: [{ href: "/guide/", label: "Review safe egg returns" }] },
  ] },
];

const faqs: CoreFaq[] = [
  { question: "How do you get Red Panda in Steal An Egg?", answer: "Current pet indexes place it in Cherry Blossom coverage. Check the live egg or source label in that biome and confirm the hatch result before treating a route as exact." },
  { question: "Is Red Panda a pet or an egg?", answer: "Red Panda is the pet name used here. Red Panda egg is common player wording for the source question, not a verified official item title." },
  { question: "What rarity is Red Panda?", answer: "Recent independent indexes commonly call it Mythic. Read the rarity label on your current pet panel after hatching." },
  { question: "How much income does Red Panda earn?", answer: "Use the value displayed on your own selected pet. Public snapshots can differ by version, size, mutation or other modifiers." },
  { question: "Is Red Panda worth getting?", answer: "It is useful when its actual displayed value or collection role justifies the route and risk for your account. Compare it with your weakest active pet." },
];

export default function RedPandaPage() {
  return <CoreSeoPage title="Red Panda in Steal An Egg" description={description} pathname={pathname} crumbs={[{ label: "Pets", href: "/pets/" }, { label: "Red Panda" }]} intro={["Red Panda in Steal An Egg is a Cherry Blossom pet lead in current independent indexes. Players looking for it need the source path, the rarity shown by the game and a realistic way to compare the pet with what they already own.", "This guide treats the pet name as distinct from an egg's official label. Public indexes give useful context, while the current hatch and selected pet panel provide the final answer for source, class and income in your own session."]} sections={sections} faqTitle="Red Panda FAQ" faqs={faqs} screenshots={[{ label: "Red Panda hatch and selected pet panel", filename: "steal-an-egg-red-panda.webp", description: "Reserved for an original source and result capture." }]} related={[{ href: "/pets/", label: "Pets", description: "Browse the wider pet index." }, { href: "/pets/best-pets/", label: "Best Pets", description: "Compare progression value." }, { href: "/pets/rarest-pets/", label: "Rarest Pets", description: "Understand high-tier context." }, { href: "/updates/sakura-event/", label: "Sakura Event", description: "Review Cherry Blossom context." }, { href: "/rarities/", label: "Rarities", description: "Check the named tiers." }, { href: "/eggs/", label: "Eggs", description: "Trace the egg source." }]} dataStatus={null} showVerificationNotice={false} extraSchema={[{ "@type": "Article", headline: title, description, mainEntityOfPage: `https://steal-an-egg.github.io${pathname}`, inLanguage: "en" }]} />;
}
