import { CoreSeoPage, type CoreFaq, type CoreSection } from "@/components/steal-an-egg/CoreSeoPage";
import { buildMetadata } from "@/lib/seo";

const title = "Steal An Egg Dr. Scramble Boss – Guide, Fight & Rewards";
const description = "Learn how the Dr. Scramble boss works in Steal An Egg, including where to find the encounter, fight mechanics, reported rewards, tips, and common questions.";
const pathname = "/guide/dr-scramble-boss/";
export const metadata = buildMetadata({ title, description, pathname });

const sections: CoreSection[] = [
  { title: "Who Is Dr. Scramble in Steal An Egg?", subsections: [
    { title: "The boss search and the event name", paragraphs: ["Dr. Scramble is the character named in the official Dr. Scramble's Revenge event announcement. Players searching for the Dr. Scramble boss usually want to enter the encounter, survive the fight and understand what the result earns. Current gameplay coverage describes a large mech encounter followed by a confrontation with Dr. Scramble. The event title confirms the character and story; it does not, by itself, certify a health number, phase count or permanent reward table.", "Some guides call the encounter Dr. Scramble's Mech and others shorten it to Dr. Scramble boss. Treat those as search terms for the same storyline, but read the encounter label in your current server before following an old walkthrough. This page focuses on the fight, while the updates hub handles the broader patch timeline."], links: [{ href: "/updates/", label: "See the wider update timeline" }] },
  ] },
  { title: "Where to Find the Dr. Scramble Boss", subsections: [
    { title: "Find the active entry, not a permanent coordinate", paragraphs: ["Current guides place the timed portal in the Forest Biome, though nearby landmark directions differ and the portal may be absent outside its active window. The reliable method is to look for the live event prompt or portal callout, then follow the current in-game marker. A map screenshot from one server can place you near the event while still missing an entrance that has not spawned yet.", "Before you travel, check the current server's event UI and whether the portal is visible. If a group is forming, follow the people heading to the marked entry and confirm its label. Do not assume a reported recurrence interval will remain fixed after a patch. An event card's scheduled dates and the boss's gameplay availability are related but distinct facts."], links: [{ href: "/guide/", label: "Review movement and return basics" }] },
  ] },
  { title: "How the Dr. Scramble Boss Fight Works", subsections: [
    { title: "Read each visible target", paragraphs: ["Current fight reports describe an initial mech target, an exposed inner target and a final moment involving Dr. Scramble himself. The exact number of stages is described differently across guides, so use the health bars, hit feedback and arena prompts in your session instead of counting phases from a video. If your hits stop registering, look for a changed target or an opening rather than swinging continuously at the armored model.", "Watch what the arena highlights after each major transition. A weak point can be a separate target from the large character model. Keep enough room to move while attacking and avoid standing under an animation simply to land one extra hit. This is practical fight guidance based on the observed encounter shape, not a claim about fixed damage, boss HP or invulnerability timing."], links: [{ href: "/progression/", label: "Prepare your account for harder runs" }] },
  ] },
  { title: "How to Beat Dr. Scramble", subsections: [
    { title: "A repeatable approach", paragraphs: ["Enter with the equipment you can currently use, identify the target that actually takes damage and keep moving between attacks. On a mech encounter, aim for clear hit feedback first. After an apparent defeat, wait for the arena to reveal its next cue instead of leaving immediately; a fight can continue after the first health bar disappears. If the final character becomes the target, switch your attention to that character and confirm each successful hit visually.", "A team can make it easier to observe the boss while somebody else draws attention, but do not assume a teammate's damage automatically counts for your reward. Check your own completion notice at the end. If the encounter resets or the portal closes, preserve your observations and attempt the next visible cycle rather than spending items based on an unverified respawn estimate."], links: [{ href: "/guide/", label: "Practice a safe movement route" }] },
  ] },
  { title: "Dr. Scramble Rewards", subsections: [
    { title: "Samples, mastery and what to verify", paragraphs: ["Current public gameplay guides connect the fight with Samples and a Boss Mastery track. Those are useful reward categories to check, but the exact amount per clear, milestone thresholds and item stock may change. After a completed fight, inspect the reward toast and your counters before visiting a shop. That makes it possible to distinguish a boss payout from currency earned earlier through other Dr. Scramble activities.", "Do not equate a shop listing with a guaranteed boss drop. A shop item may require currency, a mastery milestone may require several clears, and a rare egg may be offered through yet another route. This page does not publish a fixed reward rate or guaranteed high-rarity pet. Record the item name and the condition printed next to it in the live UI before planning repeated fights."], links: [{ href: "/eggs/", label: "Check egg source terminology" }] },
  ] },
  { title: "Best Tips for the Dr. Scramble Boss", subsections: [
    { title: "Prepare for a clean attempt", paragraphs: ["Start by confirming the encounter is currently active. A closed portal is not a combat problem. Have movement space, the weapon or tool shown as usable by the game, and a clear view of the boss's targets. Watch one transition carefully before trying to optimize damage. Players lose more time by attacking the wrong stage than by taking a moment to read the prompt.", "If you want a reward, finish the full sequence and check the resulting counter. A clip ending at the first mech collapse may omit a later target or a separate claim button. Keep any obtained egg safe and verify its exact source and hatch result. The pet index is useful after you have a real item, but it should not be used to infer what this boss must drop."], links: [{ href: "/pets/", label: "Compare confirmed pet records" }] },
  ] },
  { title: "Dr. Scramble Boss Not Appearing?", subsections: [
    { title: "Check the event state first", paragraphs: ["If the boss is absent, check whether the event window is active, whether the server has reached its current portal cycle and whether you are at the right entry. A public guide can show a portal that existed during a recorded run without proving it is open in every later server. The official Revenge event had a scheduled window; ongoing access after that window should be checked in game rather than assumed from the listing alone.", "If the portal appears but the arena will not progress, watch for an exposed target or a changed interaction prompt. Rejoining may help with a stale server, but first record what the game actually displayed. This keeps a missing entry, a phase transition and a potential bug from being treated as the same issue."], links: [{ href: "/updates/", label: "Check current update notes" }] },
  ] },
];

const faqs: CoreFaq[] = [
  { question: "Where is the Dr. Scramble boss?", answer: "Look for the active event portal or marker in your current server. Reported landmark directions differ, and the portal may not be visible outside its active cycle." },
  { question: "How do I beat Dr. Scramble?", answer: "Follow the target that shows hit feedback through the mech and later encounter cues. Keep moving, and check for a new target when the first health bar ends." },
  { question: "What rewards does Dr. Scramble give?", answer: "Current guides report Samples and Boss Mastery. Check the live reward toast and shop or milestone panels for exact current amounts and conditions." },
  { question: "How often does the boss appear?", answer: "A recurrence is reported in current coverage, but this page does not freeze a timer. Use your server's active portal or countdown as the current source." },
  { question: "Is the boss still available after the Revenge event?", answer: "The official event window and ongoing gameplay availability are separate. Check the current game, because the event listing alone cannot establish permanent access." },
];

export default function DrScrambleBossPage() {
  return <CoreSeoPage title="Steal An Egg Dr. Scramble Boss Guide" description={description} pathname={pathname} crumbs={[{ label: "Guide", href: "/guide/" }, { label: "Dr. Scramble Boss" }]} intro={["The Dr. Scramble boss in Steal An Egg is a timed encounter reached through a portal in the Forest Biome, according to current gameplay guides. They report a roughly 30-minute cycle: defeat the giant mech, attack its exposed core, then finish the final Dr. Scramble target.", "Completing the encounter rewards Samples and Boss Mastery in current coverage. Check the live portal timer and reward screen after updates, because availability, timing and reward details can change."]} sections={sections} faqTitle="Dr. Scramble Boss FAQ" faqs={faqs} screenshots={[{ label: "Boss portal and arena target", filename: "steal-an-egg-dr-scramble-boss.webp", description: "Reserved for a readable current encounter capture." }]} related={[{ href: "/guide/", label: "Beginner Guide", description: "Review the core game loop." }, { href: "/updates/", label: "Updates", description: "Check the wider event timeline." }, { href: "/progression/", label: "Progression", description: "Prepare resources for harder content." }, { href: "/pets/", label: "Pets", description: "Compare a real hatch result." }, { href: "/eggs/", label: "Eggs", description: "Separate source names from rewards." }]} dataStatus={null} showVerificationNotice={false} extraSchema={[{ "@type": "Article", headline: title, description, mainEntityOfPage: `https://steal-an-egg.github.io${pathname}`, inLanguage: "en" }]} />;
}
